version: '3'
services:
  is_database:
      container_name: is_mariadb
      image: mariadb:10.9.5
      volumes:
        - is_dbdata:/var/lib/mysql
      networks:
        - infinite-skin
      environment:
        - "MYSQL_DATABASE=infinite_skin"
        - "MYSQL_USER=infinite_skin"
        - "MYSQL_PASSWORD=infinite_skin"
        - "MYSQL_ROOT_PASSWORD=secret"
      ports:
        - 3306:3306

  is_frontend:
    image: is_frontend
    container_name: is_frontend
    build:
      context: ./frontend
      args:
        ENVIRONMENT: development
        NODE_ENV: development
    command: yarn start
    env_file: ./frontend/.env
    ports:
      - '8080:3000'
    networks:
      - infinite-skin
    volumes:
      - ./frontend/src:/app/src

  is_backend:
    image: is_backend
    container_name: is_backend
    build:
      context: ./backend
    env_file: ./backend/.env
    ports:
      - '8001:80'
    networks:
      - infinite-skin
    volumes:
      - ./backend/src:/app/src
      - ${MEDIA_FOLDER?error}:/app/media_folder

volumes:
  is_dbdata:

networks:
  infinite-skin:
