//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::album::Entity as Album;
pub use super::album_info::Entity as AlbumInfo;
pub use super::artist::Entity as Artist;
pub use super::series::Entity as Series;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
