//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::album::Entity as Album;
pub use super::album_info::Entity as AlbumInfo;
pub use super::artist::Entity as Artist;
pub use super::library::Entity as Library;
pub use super::series::Entity as Series;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
